baseURL = "https://engbytes.dev/"
languageCode = "en-us"
title = "Home"
theme = "hyde-hyde"
highlightjs = true
highlightjsstyle="Idea"
disqusShortname = ""
googleAnalytics = ""
staticDir = ["static/img"]

[params]
    themeColor = "theme-base-0d"
    showBuiltWith = false
[params.social]
	twitter = "eng_bytes"
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Books"
    weight = 200
    identifier = "books"
    url = "/books/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 400
    url = "/about/"
